### ISSUE TITLE
Serenity-bdd 1.0.59 doesn't support Java 6 resulting in impossibility to build Podam with Java 6

### ISSUE THREAD

**Issue by daivanov** [devopsfolks/podam#215]
Caused by: java.lang.UnsupportedClassVersionError: net/serenitybdd/maven/plugins/SerenityAggregatorMojo : Unsupported major.minor version 51.0

	at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)

	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)

	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)

	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)

	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)

	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)

	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)

	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)

	... 41 more

**Comment by daivanov** [comment]
Serenity 1.0.26 was already Java 6 incompatible, and versions below have issue with other Podam dependencies compatibility. I think dropping Java 6 support is an option here.

**Comment by mtedone** [comment]
I agree. We could move compatibility to Java 7

**Comment by daivanov** [comment]
Since Serenity is a test dependency, nothing special is needed. Actually compatibility with Java 6 might be still there, but it just cannot be verified any more.
