### ISSUE TITLE
Podam fails to find a right manufacturer, if several manufacturers are matching POJO's type hierarchy

### ISSUE THREAD

**Issue by Otanikotani** [devopsfolks/podam#234]
Pojo:

```java
    public class Foo {
        ArrayList rawArrayList;

        public ArrayList getRawArrayList() {
            return rawArrayList;
        }

        public void setRawArrayList(ArrayList rawArrayList) {
            this.rawArrayList = rawArrayList;
        }
    }
```

Test:
```java
public class FooTest {
    @Test
    public void test_() throws Exception {
        PodamFactoryImpl podamFactory = new PodamFactoryImpl();
        podamFactory.manufacturePojo(Foo.class);
    }
}
```

The test fails with exception:
```
java.lang.IllegalArgumentException: java.util.ArrayList is missing generic type arguments, expected [E], provided []
```

The error message makes a lot of sense - a raw type is used and the factory cannot figure out what to populate the list with. However, this:

```java
    public class Foo {
        List rawList;

        public List getRawList() {
            return rawList;
        }

        public void setRawList(List rawList) {
            this.rawList = rawList;
        }
    }
```

works! It gives the warning:
```
WARN  uk.co.jemos.podam.typeManufacturers.TypeManufacturerUtil - Unrecognized type E. Will use Object instead
```
but it doesn't throw an exception. I see it as inconsistency, since one would expect ArrayList to work the same way List works. 

After lurking the code, I think I found the problem. In **AbstractRandomDataProviderStrategy.getTypeValue()**:

```java
Deque<Class<?>> types = new ArrayDeque<Class<?>>();
		types.add(pojoType);
		TypeManufacturer<?> manufacturer = null;
		while (null == manufacturer && !types.isEmpty()) {

			Class<?> type = types.remove();
			manufacturer = typeManufacturers.get(type);
			if (null == manufacturer) {
				for (Class<?> iface : type.getInterfaces()) {
					types.add(iface);
				}
				type = type.getSuperclass();
				if (null != type) {
					types.add(type);
				}
			}
		}
```

It tries to find the best manufacturer for the given type. When it looks for manufacturer for type List it finds the **CollectionTypeManufacturerImpl**. However, for ArrayList it finds **ArrayTypeManufacturerImpl**! As far as I understood it happens because when it looks for the best manufacturer it does it breadth-first over interfaces implemented by the type. So for List it goes straight to looking for manufacturer for Collection type and finds it. For ArrayList:
```java
public class ArrayList<E> extends AbstractList<E>
        implements List<E>, RandomAccess, Cloneable, java.io.Serializable
```
it looks for manufacturer for Cloneable before looking for manufacturer for Collection since the latter is deeper in interface hierarchy. 

I think breadth-first approach is better in general, but in this particular case it failed. I don't see an easy solutions which can be done in the library without hardcoded exceptions. Please share if you see how to solve it. For my need I simply registered a custom manufacturer like this:
```java
        podamFactory.getStrategy().addOrReplaceTypeManufacturer(ArrayList.class, (strategy, attributeMetadata, genericTypesArgumentsMap) -> new ArrayList<>());
```
and it worked for me. But I wanted to share the problem anyways, if you think it is not a bug, please close it.

**Comment by daivanov** [comment]
Snapshot [7.0.5-2](https://oss.sonatype.org/content/repositories/snapshots/uk/co/jemos/podam/podam/7.0.5-SNAPSHOT/podam-7.0.5-20170205.182138-2.jar).

**Comment by daivanov** [comment]
I will resolve this issue, if you don't mind.

**Comment by Otanikotani** [comment]
Okay, thank you

**Comment by daivanov** [comment]
Thank you for reporting.

**Comment by daivanov** [comment]
Released in Podam 7.0.5

**Comment by DanielMack** [comment]
Um .... nope, its not released, im getting a very similar exception: 
```
java.lang.IllegalArgumentException: java.util.List is missing generic type arguments, expected [E], provided [E]
	at uk.co.jemos.podam.typeManufacturers.TypeManufacturerUtil.fillTypeArgMap(TypeManufacturerUtil.java:169)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:499)
	at uk.co.jemos.podam.api.PodamFactoryImpl.doManufacturePojo(PodamFactoryImpl.java:436)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojo(PodamFactoryImpl.java:151)
	at  ---- sorry, my classpath is confidential ---
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by daivanov** [comment]
Hi, which version of podam are you using and could you please show a POJO resulting in this exception?
From my side I could say that [7.0.5](https://mvnrepository.com/artifact/uk.co.jemos.podam/podam/7.0.5.RELEASE) is definitely released.

**Comment by DanielMack** [comment]
sure but im really busy atm and i would need to anonymize the classes first ... you may expect them in the 7 days or so

**Comment by daivanov** [comment]
It's enough to have a very schematic POJO, just like Andrey provided, which reproduce the problem. 

    public class Foo {
        ArrayList rawArrayList;

        public ArrayList getRawArrayList() {
            return rawArrayList;
        }

        public void setRawArrayList(ArrayList rawArrayList) {
            this.rawArrayList = rawArrayList;
        }
    }

The exception is related to a single field and how it's defined in terms of constructors/setting/visibility. You can see the POJO, which caused the problem from the log on debug level.

Could you also confirm you are using Podam 7.0.5?

**Comment by DanielMack** [comment]
Im currently on another version because we still rely on older API but i successfully reproduced the problem on 7.0.5, yes.

**Comment by daivanov** [comment]
So did you have any chance to find the POJO, which is causing problems?

**Comment by DanielMack** [comment]
not yet, sorry - we are being swamped with work ... ill get on it sometime if it still exists with current versions
